language: node_js
node_js:
  - 10
addons:
  apt:
    packages:
      - libgconf-2-4
branches:
  except:
  - production
cache:
  npm: true
  directories:
    - node_modules
    - ~/.cache
node_js:
- lts/*
before_install:
- chmod +x ./src/jobs/prepare_cache_key.sh
- ./src/jobs/prepare_cache_key.sh
install:
  - npm ci
script:
- npm run test
- npm run test:e2e-ci
after_success:
- chmod +x ./src/jobs/travis.sh
- chmod +x ./src/jobs/deploy.sh
- ./src/jobs/travis.sh
