name: Deploy production manual
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run deployment script
      env: 
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        chmod +x ./src/jobs/deploy.sh
        ./src/jobs/deploy.sh production
